name:                invalid-monoid
version:             0.1.0.0
github:              "haleemur/invalid-monoid"
license:             BSD3
author:              "Haleemur Ali"
maintainer:          "haleemur@gmail.com"
copyright:           ""

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/haleemur/invalid-monoid#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  invalid-monoid-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - invalid-monoid

tests:
  invalid-monoid-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - invalid-monoid
    - QuickCheck
